import { pgTable, text, timestamp, uuid, boolean, jsonb } from 'drizzle-orm/pg-core';
import { users } from './users';
import { tenants } from './tenants';

export const documents = pgTable('documents', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: uuid('tenant_id').references(() => tenants.id).notNull(),
  userId: uuid('user_id').references(() => users.id).notNull(),
  fileName: text('file_name').notNull(),
  fileUrl: text('file_url').notNull(), // Supabase Storage URL
  fileType: text('file_type'), // mime type
  size: text('size'),
  category: text('category'), // invoice, contract, report, etc.
  extractedText: text('extracted_text'), // AI OCR output
  aiSummary: text('ai_summary'), // generated by Claude
  aiMetadata: jsonb('ai_metadata'), // structured data (e.g., invoice total, date)
  isProcessed: boolean('is_processed').default(false),
  createdAt: timestamp('created_at').defaultNow(),
});
