services:
  - type: web
    name: officia
    env: node
    installCommand: npm install
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_DISABLE_ESLINT
        value: "true"
